#!/usr/bin/bash

if [[ ! -f "$BIN_DIR/nasm" ]]; then

    cd $SOURCE_DIR
    if [ ! -f nasm-2.16.01.tar.bz2 ]; then
        wget https://www.nasm.us/pub/nasm/releasebuilds/2.16.01/nasm-2.16.01.tar.bz2
    fi
    result=$?
    if [ $result -ne 0 ]; then
        echo "NASM download failed"
        exit 1
    fi
    if [[ ! -d "nasm-2.16.01" ]]; then
        tar xjvf nasm-2.16.01.tar.bz2
    fi
    cd nasm-2.16.01
    ./autogen.sh
    PATH="$BIN_DIR:$PATH" ./configure --prefix="$BUILD_DIR" --bindir="$BIN_DIR"
    make -j$(nproc)
    result=$?
    if [ $result -ne 0 ]; then
        echo "NASM compilation failed"
        exit 1
    fi
    make install
else
    echo "Found existing NASM installation: $BIN_DIR/nasm"
fi