#!/usr/bin/bash

copy_libs() {
    executable=$1
    echo "start copy libs on executable: $executable"

    process_libs() {
        count=$(ldd $executable 2>/dev/null | awk '/=> not found/ {c++} END {print c+0}')
        echo "count: $count"
        if [ "$count" -gt 0 ]; then
            names=$(ldd $executable | awk '/=> not found/ {print $1}')
            for name in $names; do
                echo "dependency name: $name"
                cp ffmpeg/lib/$name wabash
            done
            process_libs "$executable"
        fi
    }

    process_libs "$executable"
}

PYTHON_BIN="${1:-python3.10}"
echo "Using Python interpreter: $PYTHON_BIN"

cd scripts/linux

export LD_RUN_PATH='$ORIGIN'
export ACLOCAL_PATH=/usr/share/aclocal
export LIBXML2_INCLUDE_DIRS=$HOME/libxml2_build/include/libxml2
export LIBXML2_LIBRARIES=$HOME/libxml2_build/lib/libxml2.so
export PKG_CONFIG_PATH=$HOME/ffmpeg_build/lib/pkgconfig
export SDL2_DIR=$HOME/ffmpeg_build

rm -rf $HOME/ffmpeg_build
mkdir -p $HOME/ffmpeg_sources 
mkdir -p $HOME/bin
mkdir -p $HOME/sources
rm -rf $HOME/libxml2_build
mkdir -p $HOME/libxml2_sources

./prerequisites

./build_automake && \
./build_libxml2 && \
./build_nasm && \
./build_h264 && \
./build_h265 && \
./build_aac && \
./build_sdl2 && \
./build_ffmpeg

cd ../..
cp -R $HOME/ffmpeg_build ffmpeg
$PYTHON_BIN -m venv env
source env/bin/activate
pip install -v .
executable=$(ls -1 wabash/_wabash* 2>/dev/null | head -n 1)
echo "executable: $executable"
copy_libs $executable
pip install -v .
