#!/usr/bin/bash

#SOURCE_DIR=$HOME/ffmpeg_sources
#BUILD_DIR=$HOME/ffmpeg_build
#BIN_DIR=$HOME/bin

if [[ ! -f "$BUILD_DIR/lib/libSDL2.so" ]]; then
    cd $SOURCE_DIR
    if [ ! -f release-2.32.0.tar.gz ]; then
        wget -O release-2.32.0.tar.gz https://github.com/libsdl-org/SDL/archive/refs/tags/release-2.32.0.tar.gz
    fi
    result=$?
    if [ $result -ne 0 ]; then
        echo "SDL2 download failed"
        exit 1
    fi
    if [ ! -d "SDL-release-2.32.0" ]; then
        tar xzvf release-2.32.0.tar.gz
    fi
    cd SDL-release-2.32.0
    ./configure --prefix=$BUILD_DIR
    make -j$(nproc)
    result=$?
    if [ $result -ne 0 ]; then
        echo "SDL2 compilation failed"
        exi 1
    fi
    make install
else
    echo "Found existing SDL2 installation $BUILD_DIR/lib/libSDL2.so"
fi