#!/usr/bin/bash

copy_libs() {
    executable=$1
    echo "start copy libs on executable: $executable"

    process_libs() {
        count=$(ldd $executable 2>/dev/null | awk '/=> not found/ {c++} END {print c+0}')
        echo "count: $count"
        if [ "$count" -gt 0 ]; then
            names=$(ldd $executable | awk '/=> not found/ {print $1}')
            for name in $names; do
                echo "dependency name: $name"
                cp $BUILD_DIR/lib/$name wabash
            done
            process_libs "$executable"
        fi
    }

    process_libs "$executable"
}

PYTHON_BIN="${1:-python3.10}"
echo "Using Python interpreter: $PYTHON_BIN"

export SOURCE_DIR=$PWD/sources
export BUILD_DIR=$PWD/stock
export BIN_DIR=$PWD/bin

export LD_RUN_PATH='$ORIGIN'
export ACLOCAL_PATH=/usr/share/aclocal
export LIBXML2_INCLUDE_DIRS=$BUILD_DIR/include/libxml2
export LIBXML2_LIBRARIES=$BUILD_DIR/lib/libxml2.so
export PKG_CONFIG_PATH=$BUILD_DIR/lib/pkgconfig
export SDL2_DIR=$BUILD_DIR

mkdir -p $SOURCE_DIR 
mkdir -p $BIN_DIR

scripts/linux/prerequisites

scripts/linux/build_automake && \
scripts/linux/build_libxml2 && \
scripts/linux/build_nasm && \
scripts/linux/build_x264 && \
scripts/linux/build_x265 && \
scripts/linux/build_aac && \
scripts/linux/build_sdl2 && \
scripts/linux/build_ffmpeg
result=$?
if [ $result -ne 0 ]; then
    echo "LIBRARY BUILD FAILED"
    exit 1
fi

#cp -R $BUILD_DIR ffmpeg
export FFMPEG_INSTALL_DIR=$BUILD_DIR
$PYTHON_BIN -m venv env
source env/bin/activate
pip install -v .
executable=$(ls -1 wabash/_wabash* 2>/dev/null | head -n 1)
echo "executable: $executable"
copy_libs $executable
pip install -v .
