#!/usr/bin/bash

#..........................
#
# Alternate download location
#
# git -C libxml2 pull 2> /dev/null || git clone --depth 1 https://github.com/GNOME/libxml2.git
#
#..........................

if [[ ! -f "$BUILD_DIR/lib/libxml2.so" ]]; then
    cd $SOURCE_DIR

    if [ ! -f "libxml2-2.14.6.tar.xz" ]; then
        wget https://download.gnome.org/sources/libxml2/2.14/libxml2-2.14.6.tar.xz
    fi
    result=$?
    if [ $result -ne 0 ]; then
        echo "LIBXML2 download failed"
        exit 1
    fi
    if [ ! -d "libxml2-2.14.6" ]; then
        tar xvf libxml2-2.14.6.tar.xz
    fi

    cd libxml2-2.14.6
    ./autogen.sh  --prefix=$BUILD_DIR --without-python
    make -j$(nproc)
    result=$?
    if [ $result -ne 0 ]; then
        echo "libxml2 compilation failed"
        exit 1
    fi
    make install
else
    echo "Found existing libxml2 installation"
fi