#!/usr/bin/bash

#SOURCE_DIR=$HOME/ffmpeg_sources
#BUILD_DIR=$HOME/ffmpeg_build
#BIN_DIR=$HOME/bin

if [[ ! -f "$BUILD_DIR/lib/libxml2.so" ]]; then
    cd $SOURCE_DIR
    git -C libxml2 pull 2> /dev/null || git clone --depth 1 https://github.com/GNOME/libxml2.git
    cd libxml2
    ./autogen.sh  --prefix=$BUILD_DIR --without-python
    make -j$(nproc)
    result=$?
    if [ $result -ne 0 ]; then
        echo "libxml2 compilation failed"
        exit 1
    fi
    make install
else
    echo "Found existing libxml2 installation"
fi