#!/usr/bin/bash

process_libs() {
    count=$(ldd $executable 2>/dev/null | awk '/=> not found/ {c++} END {print c+0}')
    echo "count: $count"
    if [ "$count" -gt 0 ]; then
        names=$(ldd $executable | awk '/=> not found/ {print $1}')
        for name in $names; do
            echo "dependency name: $name"
            cp ffmpeg/lib/$name wabash
        done
        process_libs "$executable"
    fi
}

process_libs "$executable"