#!/usr/bin/bash
#
# input is a python version SemVer, e.g. 3.10.11
# 3.10 works as well, you don't need the last dot number
# this script only works on apt packager installer
#

IFS='.'
read -ra newarr <<< "$1"
count=0
for val in "${newarr[@]}"; do
    if [ $count == 0 ]; then
        major="$val"
    fi
    if [ $count == 1 ]; then
        minor="$val"
    fi
    ((count=count+1))
done

int_minor=$((minor))

sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt update
sudo apt install -y python$major.$minor-dev
if [ int_minor -lt 12 ]; then
    sudo apt install -y python$major.$minor-distutils
fi
sudo apt install -y python$major.$minor-venv
