#!/usr/bin/bash

versions=("3.11" "3.12" "3.13")
for version in "${versions[@]}"; do
    echo "echo \"\" | scripts/linux/install_python $version"
done

#pip install build auditwheel patchelf
#export FFMPEG_INSTALL_DIR=$PWD/stock
#python -m build --sdist --wheel
#auditwheel repair dist/*.whl --plat manylinux_2_35_x86_64
