#!/usr/bin/bash

export FFMPEG_INSTALL_DIR=$PWD/stock
versions=("3.10" "3.11" "3.12" "3.13")
for version in "${versions[@]}"; do
    python$version --version
    result=$?
    if [ $result -ne 0 ]; then
        scripts/linux/install_python $version
    fi
    python$version -m venv $version
    source $version/bin/activate
    pip install --upgrade pip
    pip install build auditwheel patchelf
    python -m build --sdist --wheel
    auditwheel repair dist/*${version//./}*.whl --plat manylinux_2_35_x86_64
    pip install -v dist/*${version//./}*.whl
    deactivate
done

