#!/usr/bin/bash

copy_libs() {
    executable=$1
    echo "start copy libs on executable: $executable"

    process_libs() {
        count=$(ldd $executable 2>/dev/null | awk '/=> not found/ {c++} END {print c+0}')
        echo "count: $count"
        if [ "$count" -gt 0 ]; then
            names=$(ldd $executable | awk '/=> not found/ {print $1}')
            for name in $names; do
                echo "dependency name: $name"
                cp $FFMPEG_INSTALL_DIR/lib/$name wabash
            done
            process_libs "$executable"
        fi
    }

    process_libs "$executable"
}


if [ -z $VIRTUAL_ENV ]; then
    echo "**"
    echo "** This script is meant to be run inside a virtual environment"
    echo "**"
    exit 1
fi

cp -R vm/shared/wheelhouse .
tar xvf vm/shared/stock.tar.gz
export FFMPEG_INSTALL_DIR=$PWD/stock
pip install -v .
executable=$(ls -1 wabash/_wabash* 2>/dev/null | head -n 1)
echo "executable: $executable"
copy_libs "$executable"
pip install -v .
