#!/usr/bin/bash

cp -R wheelhouse
tar xvf vm/shared/stock.tar.gz
export FFMPEG_INSTALL_DIR=$PWD/stock
echo "FFMPEG_INSTALL_DIR: $FFMPEG_INSTALL_DIR"
pip install -v .

input_file="vm/shared/filenames.txt"

while IFS= read -r line; do
  cp "stock/lib/$line" wabash
done < "$input_file"

pip install -v .