#!/bin/bash
BASE=$PWD

if [ ! -f "$BUILD_DIR/lib/libx264.dylib" ]; then
    cd $SOURCE_DIR
    git -C x264 pull 2> /dev/null || git clone --depth 1 https://code.videolan.org/videolan/x264.git
    cd x264
    PATH="$BUILD_DIR/bin:$PATH" PKG_CONFIG_PATH="$BUILD_DIR/lib/pkgconfig" ./configure --prefix="$BUILD_DIR" --bindir="$BUILD_DIR/bin" --enable-shared --enable-pic
    PATH="$BUILD_DIR/bin:$PATH" make -j$(nproc)
    result=$?
    if [ $result -ne 0 ]; then
        echo "x264 compilation failed"
        exit 1
    fi
    make install
else
    echo "Found existing x264 library at $BUILD_DIR/lib/libx264.dylib"
fi

cd $BASE