#!/bin/bash

BASE=$PWD

if [ ! -f "$BUILD_DIR/lib/libavcodec.dylib" ]; then
    cd $SOURCE_DIR
    if [ -f "$SOURCE_DIR/ffmpeg-snapshot.tar.bz2" ]; then
        wget -O ffmpeg-snapshot.tar.bz2 https://ffmpeg.org/releases/ffmpeg-snapshot.tar.bz2
    fi
    result=$?
    if [ $result -ne 0 ]; then
        echo "ffmpeg download failed"
        exit 1
    fi
    if [[ ! -d "ffmpeg" ]]; then
        tar xjvf ffmpeg-snapshot.tar.bz2
    fi
    cd ffmpeg
    PATH="$BUILD_DIR/bin:$PATH" PKG_CONFIG_PATH="$BUILD_DIR/lib/pkgconfig" ./configure \
        --prefix="$BUILD_DIR" \
        --extra-cflags="-I$BUILD_DIR/include" \
        --extra-ldflags="-L$BUILD_DIR/lib" \
        --extra-libs="-lpthread -lm" \
        --ld="g++" \
        --bindir="$BUILD_DIR/bin" \
        --enable-shared \
        --enable-pic \
        --disable-static \
        --enable-gpl \
        --enable-libfdk-aac \
        --enable-libx264 \
        --enable-libx265 \
        --enable-nonfree && \
    PATH="$BUILD_DIR/bin:$PATH" make -j$(nproc)
    make install && \
    result=$?
    if [ $result -ne 0 ]; then
        echo "ffmpeg download failed"
        exit 1
    fi
    hash -r
else
    echo "Found existing ffmpeg libraries at $BUILD_DIR/lib"
fi

cd $BASE