#!/bin/bash
BASE=$PWD
if [ ! -f "$BUILD_DIR/lib/libfdk-aac.dylib" ]; then
    cd $SOURCE_DIR
    git -C fdk-aac pull 2> /dev/null || git clone --depth 1 https://github.com/mstorsjo/fdk-aac
    cd fdk-aac
    autoreconf -fiv
    ./configure --prefix="$BUILD_DIR" --enable-shared
    make -j$(nproc)
    result=$?
    if [ $result -ne 0 ]; then
        echo "aac compilation failed"
        exit 1
    fi
    make install
else
    echo "Found existing aac library at $BUILD_DIR/lib/libfdk-aac.dylib"
fi
cd $BASE