#!/bin/bash

cd wabash
rm -R __pycache__
rm _wabash.*.so
cd ..
export FFMPEG_INSTALL_DIR=$PWD/stock
echo "FFMPEG_INSTALL_DIR: $FFMPEG_INSTALL_DIR"
# copy the dependecies to the staging direcotyr, using only the files, not the symlinks
find "$FFMPEG_INSTALL_DIR/lib" -type f -print0 | while IFS= read -r -d $'\0' file; do
  cp "$file" wabash
done
pip install -v .
