#!/bin/bash

find_dependencies() {
    echo "find deps $1"
    for name in $(otool -l $1 | grep -A5 LC_LOAD_DYLIB | grep name | awk '{print $2}'); do
        echo "name: $name"
        dir_name=$(dirname $name)
        file_name=$(basename $name)
        if [ $dir_name != "/usr/lib" ]; then
            for sub_name in $(otool -l $name | grep -A5 LC_LOAD_DYLIB | grep name | awk '{print $2}'); do
                if [[ -e $sub_name ]]; then
                    echo "sub_name $sub_name"
                fi
            #find_dependencies "$name"
            done
        fi
    done
}


echo $VIRTUAL_ENV
#pip install -v .
pyname=$(ls $VIRTUAL_ENV/lib | awk '{print $1}')
pydir="$VIRTUAL_ENV/lib/$pyname/site-packages"
moddir="$pydir/wabash"
/bin/ls "$moddir" | grep "_wabash"
modname="$pydir/wabash/$(/bin/ls -1 "$moddir" | grep "_wabash")"
export executable=$modname
export sourcedir=wabash

echo "executable: ${executable}"
find_dependencies "$executable"





#scripts/mac/copy_libs
#scripts/mac/install_name

#rm -rf dist

#pip uninstall -y wabash

#assets/scripts/mac_pkgs
#deactivate
